version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: order id corresponding with purchase
          - name: products_id
            description: products within an order and purchase
          - name: revenue
            description: income from purchase
          - name: quantity
            description: total items purchased
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
      
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / purchase price per product
        columns:
          - name: products_id
            description: id of each product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: total cost per product
      
      - name: ship
        identifier: raw_gz_ship
        description: Greenweez shipping data / fee paid alongside costs associated with each order
        columns:
          - name: orders_id
            description: unique order ids
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee paid by customer
          - name: logcost
            description: logistical costs paid by the business
          - name: ship_cost
            description: shipping costs paid by the business
      
      - name: adwords
        identifier: raw_gz_adwords
        description: campaign data from adwords
        data_tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
        columns:
          - name: date_date
            description: date of campaign
            data_tests:
              - not_null
          - name: paid_source
            description: campaign source
            data_tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign pushed per day
            data_tests:
              - not_null
          - name: camPGN_name
            description: location of campaign
            data_tests:
              - not_null          
          - name: ads_cost
            description: cost to push campaign
            data_tests:
              - not_null
          - name: impression
            description: opened campaign
            data_tests:
              - not_null
          - name: click
            description: followed through link
            data_tests:
              - not_null

      - name: bing
        identifier: raw_gz_bing
        description: campaign data from bing
        data_tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
        columns:
          - name: date_date
            description: date of campaign
            data_tests:
              - not_null
          - name: paid_source
            description: campaign source
            data_tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign pushed per day
            data_tests:
              - not_null
          - name: camPGN_name
            description: location of campaign
            data_tests:
              - not_null
          - name: ads_cost
            description: cost to push campaign
            data_tests:
              - not_null
          - name: impression
            description: opened campaign
            data_tests:
              - not_null
          - name: click
            description: followed through link
            data_tests:
              - not_null

      - name: criteo
        identifier: raw_gz_criteo
        description: campaign data from criteo
        data_tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
        columns:
          - name: date_date
            description: date of campaign
            data_tests:
              - not_null
          - name: paid_source
            description: campaign source
            data_tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign pushed per day
            data_tests:
              - not_null
          - name: camPGN_name
            description: location of campaign
            data_tests:
              - not_null
          - name: ads_cost
            description: cost to push campaign
            data_tests:
              - not_null
          - name: impression
            description: opened campaign
            data_tests:
              - not_null
          - name: click
            description: followed through link
            data_tests:
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        description: campaign data from adwords
        data_tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
        columns:
          - name: date_date
            description: date of campaign
            data_tests:
              - not_null
          - name: paid_source
            description: campaign source
            data_tests:
              - not_null 
          - name: campaign_key
            description: key of the campaign pushed per day
            data_tests:
              - not_null
          - name: camPGN_name
            description: location of campaign
            data_tests:
              - not_null
          - name: ads_cost
            description: cost to push campaign
            data_tests:
              - not_null
          - name: impression
            description: opened campaign
            data_tests:
              - not_null
          - name: click
            description: followed through link
            data_tests:
              - not_null
models:
  - name: int_sales_margin
    description: intermediate table showing margin and purchase cost
    data_tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
    columns:
      - name: date_date
        description: date of the purchase
        data_tests:
          - not_null
      - name: orders_id
        description: id of purchase
        data_tests:
          - not_null
      - name: products_id
        description: id of each product
        data_tests:
          - not_null
      - name: revenue
        description: income per order
        data_tests:
          - not_null
      - name: quantity
        description: amount of items ordered
        data_tests:
          - not_null
      - name: purchase_cost
        description: cost to gz for purchasing products
        data_tests:
          - not_null
      - name: margin
        description: profit
        data_tests:
          - not_null
  
  - name: int_orders_margin
    description: table aggregated by order id and date
    columns:
      - name: date_date
        description: date per order id
        data_tests:
          - not_null
      - name: orders_id
        description: distinct order ids 
        data_tests:
          - unique
          - not_null
      - name: revenue
        description: total revenue per order
        data_tests:
          - not_null
      - name: quantity
        description: total amount of items in order
        data_tests:
          - not_null
      - name: purchase_cost
        description: cost to greenweez aggregated by order
        data_tests:
          - not_null
      - name: margin
        description: profit per order
        data_tests:
          - not_null    


  - name: int_orders_operational
    description: added from ship table costs and fees 
    columns:
      - name: orders_id
        description: order id
        data_tests:
          - unique
          - not_null
      - name: date_date
        description: date
        data_tests:
          - not_null
      - name: revenue
        description: income per order
        data_tests:
          - not_null        
      - name: purchase_cost
        description: cost to company per order
        data_tests:
          - not_null
      - name: operational_margin
        description: margin after costs
        data_tests:
          - not_null
      - name: quantity
        description: amount of goods purchased
        data_tests:
          - not_null
      - name: margin
        description: profit
        data_tests:
          - not_null        
      - name: logcost
        description: logistical costs
        data_tests:
          - not_null
      - name: ship_cost
        description: shipping cost
        data_tests:
          - not_null
      - name: shipping_fee
        description: fee paid by customer
        data_tests:
          - not_null

  - name: finance_days
    description: aggregates of sales data by date
    columns:
      - name: date_date
        description: the date
        data_tests:
          - not_null
          - unique
      - name: nb_transactions
        description: sum of order ids on a day
        data_tests:
          - not_null     
      - name: revenue
        description: revenue for a day
        data_tests:
          - not_null
      - name: average_basket
        description: average number of items in the basket of an order for a day
        data_tests:
          - not_null
      - name: margin
        description: profit
        data_tests:
          - not_null
      - name: operational_margin
        description: the profit margin for a day taking into account COGS and operating costs
        data_tests:
          - not_null
      - name: purchase_cost
        description: purchase cost for a day (total COGS)
        data_tests:
          - not_null
      - name: shipping_fee
        description: total cost in shipping fees charged to customers per day
        data_tests:
          - not_null
      - name: logcost
        description: logistic costs in shipping an order
        data_tests:
          - not_null
      - name: quantity
        description: total number of items sold in a day
        data_tests:
          - not_null
      - name: ship_cost
        description: shipping costs to business
        data_tests:
          - not_null

  - name: int_campaigns
    description: cost of ads, success metrics and campaign key for a specific day and campaign key for all of the ad sources
    data_tests:
      - unique:
          column_name: "(date_date || '_' || campaign_key)"
    columns:
      - name: date_date
        description: the date
        data_tests:
          - not_null
      - name: paid_source
        description: company providing advertisement
        data_tests:
          - not_null
      - name: campaign_key
        description: unique identifier of a campaign
        data_tests:
          - not_null
      - name: campaign_name
        description: name of campaign
        data_tests:
          - not_null
      - name: ads_cost
        description: how much is being charged for this campaign on this day
        data_tests:
          - not_null
      - name: impression
        description: nb of adverts viewed on a day for a campaign
        data_tests:
          - not_null
      - name: click
        description: nb of clicks on an advert on a day for a campaign
        data_tests:
          - not_null
    
  - name: int_campaigns_day
    description: aggregated cost, impressions and clicks for each day of campaigns
    columns:
      - name: date_date
        description: date of aggregation
        data_tests:
          - unique
          - not_null
      - name: ads_cost
        description: total cost of campaigns per day
        data_tests:
          - not_null
      - name: ads_impression
        description: total views per day
        data_tests:
          - not_null
      - name: ads_clicks
        description: total clicked on link from campaign
        data_tests:
          - not_null
  
  - name: finance_campaigns_day
    description: added campaign data to financial aggregations per day
    columns:
      - name: date_date
        description: date of enterprise
        data_tests:
          - unique
          - not_null
      - name: ads_margin
        description: margin after operational and ad costs taken into a count
        data_tests:
          - not_null
      - name: average_basket
        description: average number of items in the basket of an order for a day
        data_tests:
          - not_null
      - name: operational_margin
        description: the profit margin for a day taking into account COGS and operating costs
        data_tests:
          - not_null
      - name: ads_cost
        description: total cost of campaigns per day
        data_tests:
          - not_null
      - name: ads_impression
        description: total views per day
        data_tests:
          - not_null
      - name: ads_clicks
        description: total clicked on link from campaign
        data_tests:
          - not_null
      - name: quantity
        description: total number of items sold in a day
        data_tests:
          - not_null
      - name: revenue
        description: revenue for a day
        data_tests:
          - not_null
      - name: margin
        description: profit
        data_tests:
          - not_null
      - name: purchase_cost
        description: purchase cost for a day (total COGS)
        data_tests:
          - not_null
      - name: shipping_fee
        description: total cost in shipping fees charged to customers per day
        data_tests:
          - not_null
      - name: logcost
        description: logistic costs in shipping an order
        data_tests:
          - not_null
      - name: ship_cost
        description: shipping costs to business
        data_tests:
          - not_null

  - name: finance_campaigns_month
    description: added campaign data to financial aggregations per month
    columns:
      - name: datemonth
        description: date of enterprise aggregated by month
        data_tests:
          - unique
          - not_null
      - name: ads_margin
        description: margin after operational and ad costs taken into a count
        data_tests:
          - not_null
      - name: average_basket
        description: average number of items in the basket of an order for a day
        data_tests:
          - not_null
      - name: operational_margin
        description: the profit margin for a day taking into account COGS and operating costs
        data_tests:
          - not_null
      - name: ads_cost
        description: total cost of campaigns per day
        data_tests:
          - not_null
      - name: ads_impression
        description: total views per day
        data_tests:
          - not_null
      - name: ads_clicks
        description: total clicked on link from campaign
        data_tests:
          - not_null
      - name: quantity
        description: total number of items sold in a day
        data_tests:
          - not_null
      - name: revenue
        description: revenue for a day
        data_tests:
          - not_null
      - name: margin
        description: profit
        data_tests:
          - not_null
      - name: purchase_cost
        description: purchase cost for a day (total COGS)
        data_tests:
          - not_null
      - name: shipping_fee
        description: total cost in shipping fees charged to customers per day
        data_tests:
          - not_null
      - name: logcost
        description: logistic costs in shipping an order
        data_tests:
          - not_null
      - name: ship_cost
        description: shipping costs to business
        data_tests:
          - not_null